name: Continuous integration
on:
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      SBT_NATIVE_CLIENT: true
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Run unit tests 
        run: sbt test